<a href="https://colab.research.google.com/github/KonstantinosParaskevopoulos/Free-Time-Projects/blob/main/mlp_mnist_colab_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MLP MNIST 9x9 (Google Colab Edition)

Αυτό το notebook τρέχει πλήρως το project στο Colab, με χρήση GPU.

In [1]:
# Ενεργοποίηση GPU (βεβαιώσου ότι στο Runtime → Change runtime type → GPU είναι επιλεγμένο)

In [2]:
# Ανέβασε το αρχείο ZIP που σου έδωσε το ChatGPT
from google.colab import files
uploaded = files.upload()

Saving mlp_mnist_9x9.zip to mlp_mnist_9x9.zip


In [3]:
# Αποσυμπίεση του ZIP
!unzip mlp_mnist_9x9.zip -d mlp_mnist_9x9
%cd mlp_mnist_9x9

Archive:  mlp_mnist_9x9.zip
  inflating: mlp_mnist_9x9/evaluate.py  
  inflating: mlp_mnist_9x9/README.md  
  inflating: mlp_mnist_9x9/requirements.txt  
  inflating: mlp_mnist_9x9/train.py  
   creating: mlp_mnist_9x9/utils/
  inflating: mlp_mnist_9x9/utils/preprocess.py  
/content/mlp_mnist_9x9


In [4]:
# Εγκατάσταση απαιτήσεων
!pip install -r requirements.txt

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.5/104.5 kB 6.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 81.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 110.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [5]:
# Εκπαίδευση του MLP
!python train.py

2025-06-10 22:52:41.067288: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1749595961.091351    2524 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1749595961.098395    2524 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-06-10 22:52:41.121910: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/flatten

In [6]:
# Αξιολόγηση του μοντέλου
!python evaluate.py

2025-06-10 22:53:48.648850: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1749596028.686943    2970 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1749596028.698402    2970 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-06-10 22:53:48.735168: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-06-10 22:54:09.146727: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL

Μπορείς να συνεχίσεις με quantization ή εξαγωγή TFLite αρχείου αφού ολοκληρωθεί η εκπαίδευση.

> Προσθήκη blockquote



In [8]:
import tensorflow as tf
import numpy as np

# Φόρτωση του εκπαιδευμένου μοντέλου
model = tf.keras.models.load_model('models/best_model.h5')

for i, layer in enumerate(model.layers):
    if isinstance(layer, tf.keras.layers.Dense):
        weights, biases = layer.get_weights()
        print(f"\n# Layer {i} ({layer.name})")
        print(f"Weights shape: {weights.shape}")
        print("Weights:")
        print(np.round(weights * 128).astype(int))  # Quantize σε Q7 (7 bits για fraction)
        print("Biases:")
        print(np.round(biases * 128).astype(int))


# Layer 1 (dense)
Weights shape: (81, 100)
Weights:
[[  34  -27   28 ...    1   26   12]
 [  34  -92  -23 ...  -21    4   -5]
 [  49 -129  -37 ...  -89   31   49]
 ...
 [  77    8  -64 ...  -81  -37  -51]
 [  68   47  -26 ...  -23  -71   -7]
 [  -4   34  -43 ...   26   20  -12]]
Biases:
[ 17  34   1  15   5  13  10  20   1  22   1  18 -12  12   1  32  18 -10
  -3  23   1  26  28  27  -2  -2   6  -9 -19   7  18   9  13   6  16   6
  32  19  11  -3   8   7  36  22  14  -8  32  19  11  23   1  24  -4  22
   5  11  13  -2   7  17 -18   6  25   7  14  28  10  -6   3  11   0  26
 -11  18   0  -4  36  -1  29   4  17  10  16  40  -6  11  17  57  16  -6
 -16   3  -2  21  -3   0   2  10  -4  25]

# Layer 2 (dense_1)
Weights shape: (100, 10)
Weights:
[[  76   27 -218  -23   11   70   25   98 -111   14]
 [ -37 -116   71  -15   40   72 -176   78  -66   11]
 [  52  -63  -16  -28   28    1   32   47   27  -50]
 [ -26 -131   75  -99   29   18   60 -114   42   44]
 [  57   25   70   23 -149   57   16 

In [10]:
import tensorflow as tf
from utils.preprocess import load_and_downsample

# Φόρτωση του εκπαιδευμένου μοντέλου
model = tf.keras.models.load_model('models/best_model.h5')

# Φόρτωση test set (για representative dataset)
(_, _), (x_test, _) = load_and_downsample()

# Representative dataset για quantization (απαιτείται για int8)
def representative_data_gen():
    for i in range(100):
        img = x_test[i:i+1]
        yield [img.astype(np.float32)]

# Converter
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]

# Όλα int8
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8

# Convert and save
tflite_model = converter.convert()
with open("models/mlp_9x9_quant.tflite", "wb") as f:
    f.write(tflite_model)

Saved artifact at '/tmp/tmpzdo9uomi'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 9, 9), dtype=tf.float32, name='input_layer')
Output Type:
  TensorSpec(shape=(None, 10), dtype=tf.float32, name=None)
Captures:
  133061420329168: TensorSpec(shape=(), dtype=tf.resource, name=None)
  133061420331664: TensorSpec(shape=(), dtype=tf.resource, name=None)
  133061420331088: TensorSpec(shape=(), dtype=tf.resource, name=None)
  133061420332624: TensorSpec(shape=(), dtype=tf.resource, name=None)


/usr/local/lib/python3.11/dist-packages/tensorflow/lite/python/convert.py:997: UserWarning: Statistics for quantized inputs were expected, but not specified; continuing anyway.
  warnings.warn(


In [11]:
from google.colab import files
files.download("models/mlp_9x9_quant.tflite")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>